<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title>aishikrehman.com Sitemap</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <style type="text/css">
          body {
            font-family: Arial, sans-serif;
            font-size: 14px;
            color: #333;
            background-color: #f9f9f9;
            margin: 0;
            padding: 0;
          }
          a {
            color: #007acc;
            text-decoration: none;
          }
          a:hover {
            text-decoration: underline;
          }
          table {
            border-collapse: collapse;
            width: 100%;
            margin-top: 20px;
            background-color: #ffffff;
            border: 1px solid #ddd;
            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
          }
          th {
            text-align: left;
            padding: 12px;
            background-color: #007acc;
            color: #ffffff;
            font-size: 14px;
          }
          td {
            font-size: 12px;
            padding: 10px;
            text-align: left;
            border-bottom: 1px solid #ddd;
          }
          tr:nth-child(odd) td {
            background-color: #f9f9f9;
          }
          tr:hover td {
            background-color: #e1f3fe;
          }
          #content {
            margin: 20px auto;
            padding: 2% 5%;
            max-width: 1000px;
          }
          h1 {
            color: #333;
            text-align: center;
            font-size: 28px;
            margin-bottom: 20px;
          }
          .desc {
            margin: 15px 0;
            line-height: 1.6em;
            font-size: 16px;
          }
          .desc a {
            color: #007acc;
            font-weight: bold;
          }
          .desc a:hover {
            text-decoration: underline;
          }
          .table-header {
            font-size: 14px;
            font-weight: bold;
          }
        </style>
      </head>
      <body>
        <div id="content">
          <h1>XML Sitemap</h1>
          <p class="desc">This is a sitemap generated by <a href="https://gohugo.io" target="_blank">Hugo</a> to allow search engines to discover this blog's content.</p>
          <p class="desc">The XSL style is adapted from <a href="https://ghost.org" target="_blank">Ghost</a>.</p>
          <table id="sitemap" cellpadding="3">
            <thead>
              <tr>
                <th width="60%">URL (<xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> total)</th>
                <th title="Priority" width="10%">Prio</th>
                <th title="Change Frequency" width="10%">Ch. Freq.</th>
                <th title="Last Modification Time" width="20%">Last Modified</th>
              </tr>
            </thead>
            <tbody>
              <xsl:variable name="lower" select="'abcdefghijklmnopqrstuvwxyz'"/>
              <xsl:variable name="upper" select="'ABCDEFGHIJKLMNOPQRSTUVWXYZ'"/>
              <xsl:for-each select="sitemap:urlset/sitemap:url">
                <tr>
                  <td>
                    <xsl:variable name="itemURL">
                      <xsl:value-of select="sitemap:loc"/>
                    </xsl:variable>
                    <a href="{$itemURL}">
                      <xsl:value-of select="sitemap:loc"/>
                    </a>
                  </td>
                  <td>
                    <xsl:value-of select="concat(sitemap:priority*100,'%')"/>
                  </td>
                  <td>
                    <xsl:value-of select="concat(translate(substring(sitemap:changefreq, 1, 1),concat($lower, $upper),concat($upper, $lower)),substring(sitemap:changefreq, 2))"/>
                  </td>
                  <td>
                    <xsl:value-of select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,5)))"/>
                  </td>
                </tr>
              </xsl:for-each>
            </tbody>
          </table>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>